### ISSUE TITLE
Company 3 just realised about the format

### ISSUE THREAD

**Issue by Younext19** [oussamabouchikhi/companies-sponsoring-visas-netherlands#5]
| Packaly | Utrecht/NL | Engineering | https://jobs.packaly.com/ | N/A |

**Comment by oussamabouchikhi** [comment]
Hi @Younext19. Thanks for you PR.
In fact the link as specified in the README file should take us to the careers page, so it should be https://jobs.packaly.com/ instead

**Comment by Younext19** [comment]
Hi @oussamabouchikhi 
Ow Yeah right, i will edit it, thank you for your response
